name: linter

on: push

jobs: 
  super-lint: 
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run super-linter
        uses: github/github-actions@v3
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: 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